[project]
name = "api-yatube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgiref==3.5.2",
    "attrs==22.1.0",
    "django==3.2",
    "djangorestframework==3.12.4",
    "iniconfig==1.1.1",
    "packaging==21.3",
    "pillow==9.3.0",
    "pluggy==0.13.1",
    "py==1.11.0",
    "pyparsing==3.0.9",
    "pytest==6.2.4",
    "pytest-django==4.4.0",
    "pytest-pythonpath==0.7.3",
    "pytz==2022.6",
    "sqlparse==0.4.3",
    "toml==0.10.2",
]

[tool.ruff]
line-length = 78
